### ISSUE TITLE
Teams?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/ring-wrappers#3]
How are we going to manage the teams for this? Should the AEAD team own `ring-aead` and the Digest team own `ring-digest`, or should we make a new team just for ring-wrappers?

**Comment by newpavlov** [comment]
I am not sure. I guess for consistency we should add a new team, but the number of teams already exceeds number of members, so one may call it excessive. :)

**Comment by newpavlov** [comment]
I've created the `ring-wrappers` team, so we can transfer crate access to it.
